### ISSUE TITLE
one big weakness

### ISSUE THREAD

**Issue by dominictarr** [feross/infinite-app-cache#2]
So, there is one significant weakness to this idea.
(in the case of the compromised sysadmin model)

If you cache `/` it never rerequests the page,
but if you open another url, it will request the site.
So, the server is compromised, and then the user fooled into
going to a non-cached url then the client will request that page,
which could contain javascript which is now running in the same domain
as localStorage, etc so you can just modify the code or hashes in localstorage.

I don't think this is a deal breaker, necessarily, but it's certainly a let down.
At least, it does make the compromised sysadmin quite a bit more difficult,
and maybe there is other things that can make it even more difficult.

Maybe if you have signatures that must verify before the code in localStorage is ran? hmm, they could still get your data - so, I guess you would need to encrypt that.... so I guess it becomes phishing, and you hope that the user notices the URL is wrong.

**Comment by feross** [comment]
If you encrypt the data in localstorage so the user has to decrypt it with a password (saved only in his/her head), then there's no problem with data being stolen. Still, the attacker could corrupt the data so the user loses his offline data, but that's still MUCH better than the data being stolen.

But the phishing case is still a problem. If they get the user to visit a page on the same domain then they can throw up a login page with very similar UI (with whatever indicators we use to let the user know they're using a cached a version) as the real page. So that's tough.

**Comment by feross** [comment]
One potential solution would be ServiceWorkers, which are coming to Chrome soon. They were mentioned in @HenrikJoreteg's recent blog post: https://blog.andyet.com/2014/01/17/web-has-outgrown-the-browser. Summary here: https://github.com/slightlyoff/ServiceWorker/#serviceworker-design

They give you access to domain-wide events such as network fetches and let you script the cache. So, depending on how they work, the could let you script the cache so that no future requests to the network are allowed.

Or, better, most of the requests to the network would be rejected, but certain requests for data (which are safely parsed in a certain code path) would be allowed to go through.

**Comment by dominictarr** [comment]
Actually, phishing would be trivial, because you could load the page at `https://app-domain.com/TEHE`
and then immediately change to `https://app-domain.com` by pushing to the url history. The user might see the domain flash, if they are lucky. Still, they would still need to trick the user into visiting the wrong path.

ServiceWorkers look awesome! If we get an secure app pattern working well with AppCache,
we could probably prod ServiceWorkers in the right direction, since it looks like the spec is only so far...

You know you are pushing javascript to the edge when you are plotting to influence spec committees.

Oh, another thing you could do, is make the bootloader completely standard, so anyone can serve it, and you can load it from anywhere, and then load apps crossdomain via cors/ws. Then an attacker wouldn't know _which_ sysadmin to bribe/seduce/threaten.

**Comment by feross** [comment]
+100 all good ideas!

**Comment by dominictarr** [comment]
update on this:

You can use appcache fallback to specify a known page to load.

```
FALLBACK:
/ index.html
```

Which means, if you can't find something under /, just use `/index.html` instead.
hmm, this will still request to the server, but when it gets a 404 (!) it displays `index.html` instead.

this article describes using a `/` in a fallback section
http://diveintohtml5.info/offline.html#fallback
but I'm not seeing it recursively match `/`, only going into the next directory...

**Comment by feross** [comment]
Cool, thanks for the update. What are you planning to use this for, btw?

**Comment by dominictarr** [comment]
yeah, I'm working on a thing here [offlinerify](https://github.com/dominictarr/offlinerify)

**Comment by dominictarr** [comment]
Oh, answered wrong question. I there is lots of stuff, one thing is https://github.com/dominictarr/mokuai-map (offlineable browser maps - will store the map tiles in indexeddb) probably this too: https://github.com/dominictarr/bed

these don't require a _paranoid_ level of security, but I figure the first task is to make appcache easy,
and then make it secure.

**Comment by feross** [comment]
sweet, will keep an eye out and help if there's anything i think i can help
with.

**Comment by feross** [comment]
See http://hyperboot.org/
